image: python:3.7

pages:
  script:
  - apt install git
  - pip3 install sphinx sphinx_rtd_theme numpy scipy transforms3d
  - sphinx-build docs/source public
  artifacts:
    paths:
    - public
  only:
  - master
